name: Android CI
on: workflow_dispatch

jobs:
  repo_name:
    steps:
    - name: Repo
      run: echo ${github.ref}
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo "HI All"
