name: Deploy - DEV

on: workflow_dispatch

jobs:

  deploy:
    name: Deploy to Elasticbeanstalk
    runs-on: ubuntu-latest
    steps:
       

    - name: Generate Deploy File
      env:
        VERSION: ${{ needs.push.outputs.version }}
        ZIP_FILE: ${{ needs.push.outputs.version }}
      run: |
        envsubst < ./deploy/Dockerrun.aws.json.tpl > Dockerrun.aws.json
        zip -r $ZIP_FILE.zip Dockerrun.aws.json
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: us-west-2
        application_name: classify
        environment_name: dev1-classify
        version_label: ${{ needs.push.outputs.version }}
        deployment_package: ${{ needs.push.outputs.version }}.zip
