name: Deploy - DEV

on: workflow_dispatch

jobs:

  deploy:
    name: Deploy to Elasticbeanstalk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate Deploy File
      env:
        VERSION: ${{ needs.push.outputs.version }}
        ZIP_FILE: ${{ needs.push.outputs.version }}
      run: |
        envsubst < ./deploy/Dockerrun.aws.json.tpl > Dockerrun.aws.json
        zip -r test_github_action.zip Dockerrun.aws.json
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        region: us-west-2
        application_name: classify
        environment_name: dev1-classify
        version_label: test_github_action
        deployment_package: test_github_action.zip
