name: Deploy - DEV

on: workflow_dispatch

jobs:

  push_image_job:
    name: Upload to ECR
    runs-on: ubuntu-latest
    outputs:
      pxlt_image_tag: ${{ steps.create-version.outputs.image_tag }}
      pxlt_commit_hash: ${{ steps.create-version.outputs.commit_hash }}
    steps:

      - name: Checkout
        run: echo ${GITHUB_REF}
