name: Android CI
on:
  workflow_dispatch:
    inputs:
      msg:
        default: ${{ github.repository}}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo "HI All"
